apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgre-service
    app: imran-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
      name: postgres
      app: demo-voting-app
  