apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: vo-service
    app: imran-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: voting
    app: demo-voting-app
    