apiVersion: v1
kind: Service
metadata: 
  name: newservice
spec:
  type: NodePort
  ports:
    - targetPort: 80  #pod port
      port : 80 # service port
      nodePort: 30007  #node port
  selector:
    type: myapp 
