apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicatset
  labels: 
    app: myapp 
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container-2
          image: nginx:latest      

